export const routes = {
  login: '/login',
  home: '/',
  orders: '/orders',
  ordersNew: '/orders/new',
  order: '/orders/:id',
  tasks: '/tasks',
  task: '/tasks/:id',
  customers: '/customers',
  customer: '/customers/:id',
  devices: '/devices',
  device: '/devices/:id',
  inventory: '/inventory',
  inventoryItems: '/inventory/items',
  inventoryItem: '/inventory/items/:id',
  inventoryReceipts: '/inventory/receipts',
  inventoryCounts: '/inventory/counts',
  inventoryCount: '/inventory/counts/:id',
  sales: '/sales',
  sale: '/sales/:id',
  documents: '/documents',
  document: '/documents/:id',
  documentPrint: '/documents/:id/print',
  documentTemplates: '/settings/document-templates',
  documentTemplate: '/settings/document-templates/:id',
  documentTemplatePrint: '/settings/document-templates/:id/print',
  users: '/users',
  roles: '/roles',
  role: '/roles/:id',
  settings: '/settings',
  settingsReferences: '/settings/references',
  settingsReference: '/settings/references/:setId',
  settingsFields: '/settings/fields',
  settingsFieldEntity: '/settings/fields/:entity',
  settingsOrders: '/settings/orders',
  settingsOrderStatuses: '/settings/order-statuses',
  settingsNotifications: '/settings/notifications',
  settingsServiceTemplates: '/settings/service-templates',
  auditLog: '/audit-log',
  authCallback: '/auth/callback',
  setPassword: '/set-password',
} as const

export type AppRoute = (typeof routes)[keyof typeof routes]
